Objective

The objective of Feature Engineering is to transform the raw dataset into a machine learning-ready format by creating meaningful features, encoding categorical variables, removing unnecessary columns, and preparing the dataset for feature selection and model building.

In [86]:
#Import Required Libraries
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder

Load the Dataset

In [88]:
df = pd.read_csv("../data/crop_yield_after_eda.csv")

In [89]:
df.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,Avg_Temperature,Max_Temperature,Min_Temperature
0,Arecanut,1997,Whole Year,Assam,11.209317,10.945688,2051.4,15.764969,10.038164,0.7960,23.692,33.435,14.779
1,Arhar/Tur,1997,Kharif,Assam,8.800566,8.452335,2051.4,13.356082,7.629718,0.7100,23.692,33.435,14.779
2,Castor seed,1997,Kharif,Assam,6.680855,3.135494,2051.4,11.235277,5.512461,0.2380,23.692,33.435,14.779
3,Coconut,1997,Whole Year,Assam,9.886189,18.434232,2051.4,14.441803,8.715119,5.0725,23.692,33.435,14.779
4,Cotton(lint),1997,Kharif,Assam,7.461640,6.678342,2051.4,12.016736,6.291736,0.4210,23.692,33.435,14.779

Display Dataset Information

In [90]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19689 entries, 0 to 19688
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Crop             19689 non-null  str
 1   Crop_Year        19689 non-null  int64
 2   Season           19689 non-null  str
 3   State            19689 non-null  str
 4   Area             19689 non-null  float64
 5   Production       19689 non-null  float64
 6   Annual_Rainfall  19689 non-null  float64
 7   Fertilizer       19689 non-null  float64
 8   Pesticide        19689 non-null  float64
 9   Yield            19689 non-null  float64
 10  Avg_Temperature  19689 non-null  float64
 11  Max_Temperature  19689 non-null  float64
 12  Min_Temperature  19689 non-null  float64
dtypes: float64(9), int64(1), str(3)
memory usage: 2.0 MB

Check Column Names

In [91]:
df.shape

(19689, 13)

In [92]:
print(df.columns.tolist())

['Crop', 'Crop_Year', 'Season', 'State', 'Area', 'Production', 'Annual_Rainfall', 'Fertilizer', 'Pesticide', 'Yield', 'Avg_Temperature', 'Max_Temperature', 'Min_Temperature']

Check Categorical Features

In [93]:
categorical_columns = df.select_dtypes(include='object').columns

print(categorical_columns)

Index(['Crop', 'Season', 'State'], dtype='str')

C:\Users\Ranjana\AppData\Local\Temp\ipykernel_15960\3910604682.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include='object').columns

Check Unique Values

In [95]:
for col in categorical_columns:

    print(f"\n{col}")

    print(df[col].unique())

    print("Total Categories:",df[col].nunique())

Crop
<StringArray>
[             'Arecanut',             'Arhar/Tur',           'Castor seed',
              'Coconut ',          'Cotton(lint)',          'Dry chillies',
                  'Gram',                  'Jute',               'Linseed',
                 'Maize',                 'Mesta',            'Niger seed',
                 'Onion',    'Other  Rabi pulses',                'Potato',
     'Rapeseed &Mustard',                  'Rice',               'Sesamum',
         'Small millets',             'Sugarcane',          'Sweet potato',
               'Tapioca',               'Tobacco',              'Turmeric',
                 'Wheat',                 'Bajra',          'Black pepper',
              'Cardamom',             'Coriander',                'Garlic',
                'Ginger',             'Groundnut',            'Horse-gram',
                 'Jowar',                  'Ragi',             'Cashewnut',
                'Banana',              'Soyabean',                'Barley',
               'Khesari',                'Masoor',     'Moong(Green Gram)',
   'Other Kharif pulses',             'Safflower',              'Sannhamp',
             'Sunflower',                  'Urad', 'Peas & beans (Pulses)',
        'other oilseeds',         'Other Cereals',         'Cowpea(Lobia)',
        'Oilseeds total',             'Guar seed',   'Other Summer Pulses',
                  'Moth']
Length: 55, dtype: str
Total Categories: 55

Season
<StringArray>
['Whole Year ', 'Kharif     ', 'Rabi       ', 'Autumn     ', 'Summer     ',
 'Winter     ']
Length: 6, dtype: str
Total Categories: 6

State
<StringArray>
[            'Assam',         'Karnataka',            'Kerala',
         'Meghalaya',       'West Bengal',        'Puducherry',
               'Goa',    'Andhra Pradesh',        'Tamil Nadu',
            'Odisha',             'Bihar',           'Gujarat',
    'Madhya Pradesh',       'Maharashtra',           'Mizoram',
            'Punjab',     'Uttar Pradesh',           'Haryana',
  'Himachal Pradesh',           'Tripura',          'Nagaland',
      'Chhattisgarh',       'Uttarakhand',         'Jharkhand',
             'Delhi',           'Manipur', 'Jammu and Kashmir',
         'Telangana', 'Arunachal Pradesh',            'Sikkim']
Length: 30, dtype: str
Total Categories: 30

In [96]:
df.shape

(19689, 13)

Create New Features

In [97]:
#Fertilizer per Hectare
df["Fertilizer_per_Area"] = df["Fertilizer"] / (df["Area"] + 1)

#Pesticide per Hectare
df["Pesticide_per_Area"] = df["Pesticide"] / (df["Area"] + 1)

#Rainfall per Area
df["Rainfall_per_Area"] = df["Annual_Rainfall"] / (df["Area"] + 1)

#Temperature Difference
df["Temperature_Range"] = df["Max_Temperature"] - df["Min_Temperature"]

Average Climate Index

In [98]:
df["Climate_Index"] = (
    df["Annual_Rainfall"] +
    df["Avg_Temperature"]
) / 2

Verify new Features

In [99]:
df.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,Avg_Temperature,Max_Temperature,Min_Temperature,Fertilizer_per_Area,Pesticide_per_Area,Rainfall_per_Area,Temperature_Range,Climate_Index
0,Arecanut,1997,Whole Year,Assam,11.209317,10.945688,2051.4,15.764969,10.038164,0.7960,23.692,33.435,14.779,1.291224,0.822172,168.019223,18.656,1037.546
1,Arhar/Tur,1997,Kharif,Assam,8.800566,8.452335,2051.4,13.356082,7.629718,0.7100,23.692,33.435,14.779,1.362787,0.778498,209.314442,18.656,1037.546
2,Castor seed,1997,Kharif,Assam,6.680855,3.135494,2051.4,11.235277,5.512461,0.2380,23.692,33.435,14.779,1.462764,0.717688,267.079653,18.656,1037.546
3,Coconut,1997,Whole Year,Assam,9.886189,18.434232,2051.4,14.441803,8.715119,5.0725,23.692,33.435,14.779,1.326617,0.800567,188.440605,18.656,1037.546
4,Cotton(lint),1997,Kharif,Assam,7.461640,6.678342,2051.4,12.016736,6.291736,0.4210,23.692,33.435,14.779,1.420143,0.743560,242.435261,18.656,1037.546

In [100]:
df.shape

(19689, 18)

Encode Categorical Values -Label encoding

In [101]:


le = LabelEncoder()

for col in categorical_columns:
    df[col] = le.fit_transform(df[col])

In [102]:
df.shape

(19689, 18)

Verify Data Types

In [103]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19689 entries, 0 to 19688
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Crop                 19689 non-null  int64
 1   Crop_Year            19689 non-null  int64
 2   Season               19689 non-null  int64
 3   State                19689 non-null  int64
 4   Area                 19689 non-null  float64
 5   Production           19689 non-null  float64
 6   Annual_Rainfall      19689 non-null  float64
 7   Fertilizer           19689 non-null  float64
 8   Pesticide            19689 non-null  float64
 9   Yield                19689 non-null  float64
 10  Avg_Temperature      19689 non-null  float64
 11  Max_Temperature      19689 non-null  float64
 12  Min_Temperature      19689 non-null  float64
 13  Fertilizer_per_Area  19689 non-null  float64
 14  Pesticide_per_Area   19689 non-null  float64
 15  Rainfall_per_Area    19689 non-null  float64
 16  Temperature_Range    19689 non-null  float64
 17  Climate_Index        19689 non-null  float64
dtypes: float64(14), int64(4)
memory usage: 2.7 MB

Check Null Values

In [104]:
df.isnull().sum()

Crop                   0
Crop_Year              0
Season                 0
State                  0
Area                   0
Production             0
Annual_Rainfall        0
Fertilizer             0
Pesticide              0
Yield                  0
Avg_Temperature        0
Max_Temperature        0
Min_Temperature        0
Fertilizer_per_Area    0
Pesticide_per_Area     0
Rainfall_per_Area      0
Temperature_Range      0
Climate_Index          0
dtype: int64

Remove Constant Features

In [105]:
constant_columns = []

for col in df.columns:

    if df[col].nunique() == 1:

        constant_columns.append(col)

print(constant_columns)

[]

Check constant columns

In [106]:
duplicate_columns = df.T.duplicated()

print(df.columns[duplicate_columns])

Index([], dtype='str')

Separate Features and Target

In [107]:
X = df.drop("Yield", axis=1)

y = df["Yield"]

Display Shapes

In [108]:
print("Features Shape :", X.shape)

print("Target Shape :", y.shape)

Features Shape : (19689, 17)
Target Shape : (19689,)

Verify Target

In [109]:
y.head()

0    0.7960
1    0.7100
2    0.2380
3    5.0725
4    0.4210
Name: Yield, dtype: float64

verify features

In [110]:
X.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Avg_Temperature,Max_Temperature,Min_Temperature,Fertilizer_per_Area,Pesticide_per_Area,Rainfall_per_Area,Temperature_Range,Climate_Index
0,0,1997,4,2,11.209317,10.945688,2051.4,15.764969,10.038164,23.692,33.435,14.779,1.291224,0.822172,168.019223,18.656,1037.546
1,1,1997,1,2,8.800566,8.452335,2051.4,13.356082,7.629718,23.692,33.435,14.779,1.362787,0.778498,209.314442,18.656,1037.546
2,8,1997,1,2,6.680855,3.135494,2051.4,11.235277,5.512461,23.692,33.435,14.779,1.462764,0.717688,267.079653,18.656,1037.546
3,9,1997,4,2,9.886189,18.434232,2051.4,14.441803,8.715119,23.692,33.435,14.779,1.326617,0.800567,188.440605,18.656,1037.546
4,11,1997,1,2,7.461640,6.678342,2051.4,12.016736,6.291736,23.692,33.435,14.779,1.420143,0.743560,242.435261,18.656,1037.546

Save Engineered Dataset

In [111]:
from pathlib import Path

# Current notebook location
print(Path.cwd())

# If notebook is in notebooks/
project_root = Path.cwd().parent

data_folder = project_root / "data"
data_folder.mkdir(exist_ok=True)  # Creates the folder if it doesn't exist
df.to_csv(data_folder / "crop_yield_feature_engineered.csv", index=False)

c:\Users\Ranjana\Crop_Yield_Prediction\notebooks